### ISSUE TITLE
能否指导下如何通过这个项目更高效的学习python？

### ISSUE THREAD

**Issue by todayjt** [hyansuper/rcute-cozmars-server#34]
**感谢你创造这个开源项目，很敬佩；**
       真的很喜欢这个项目，所以想通过对ructe的兴趣维持学习python的兴趣。现在正一点点慢慢的摸索学习中，但思路有点混乱。现阶段我是通过一点点摸索整个项目的所有库一点点了解rcute。但不知这样的办法是否更适合，感觉您做这个项目的额初衷好像也是为了教育。不知是否可以指点下学习思路或路线。或者您有开设培训班么？我想报名~~
        还有一个小问题，在了解各个库的过程中没有找到关于表情显示的内容。还望指点下.....

**Comment by hyansuper** [comment]
谢谢
表情是客户端程序rcute-cozmars里有一个eye_animation.py程序，写死的。用opencv画好每一帧然后把数据发给树莓派，对树莓派来说显示表情和显示文字没有区别，他只是接收像素数据，用adafruit-rgb-display这个库去控制显示屏。
如果是想要用python控制硬件，adafruit circuit python库有很多模块挺好用。
然后就是一些服务器客户端的通讯模块，比如websockets, sanic，等，这些看官方教程就行。
没有培训班，只是个人兴趣。有些库也是用到才去学，比如pyaudio, sound-device，等处理声音的。这些也是看看文档

**Comment by todayjt** [comment]
好的，我先一个一个看研究下。很感谢你无私的帮助！

**Comment by todayjt** [comment]
那么，rucute中的eye_animation.py程序，就相当于与一段视频。opencv就相当于与解码器，解码后视频流导入到控制屏幕的dispay中播放。是这么个概念吧？ opencv我还只会打开视频文件和图片。要学会操作这个过程，我应该先把opencv了解到什么程度呢？或者还是应该先从哪个库开始学起？adafruit_rgb_display.rgb这个库的资料我看了，现在只能改变屏幕的颜色，如果不通过你的程序，甚至都不知如何打字显示在屏幕上。因为这个库里，没有具体的关于这方面的案例~~或者您可以知道下我从何入手呢？

**Comment by hyansuper** [comment]
我的笨办法基本就是用opencv画两个矩形当眼睛
案例 就是看看文档或github的example或[API](https://docs.circuitpython.org/projects/rgb_display/en/latest/api.html)

**Comment by hyansuper** [comment]
> 感觉您做这个项目的额初衷好像也是为了教育

用作教育是指用rcute-cozmars 封装好的那套api，你现在是要探究如何实现就有难度了，当然也更意思

**Comment by todayjt** [comment]
哈哈，确实感受到难度了~~ 您是做软件这方面工作的么？

**Comment by todayjt** [comment]
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/Users/jintian/PycharmProjects/rcute_jt/ai.py", line 5, in <module>
    wwd = ai.WakeWordDetector()
  File "/Users/jintian/Library/Python/3.9/lib/python/site-packages/rcute_ai/wake_word_detection_vosk.py", line 12, in __init__
    lang_file = util.vosk_map[lang]
AttributeError: module 'rcute_ai.util' has no attribute 'vosk_map'

这段报错 是 我环境变量没设置好还是？

**Comment by hyansuper** [comment]
应该是没有正确配置好 https://rcute-ai.readthedocs.io/zh_CN/latest/installation.html

**Comment by todayjt** [comment]
您好，在研究利用树莓派控制那块屏幕遇到问题。可以用屏幕播放图片，但我导入的图片会自动向下移动，这个困扰了很久，因为初学，所以对您写的类分析不太明白，如果解释起来很麻烦，能否指导下，解决这个问题的学习方向么？是去学习opencv库还是？

**Comment by todayjt** [comment]
手臂和前进后退能用异步一起执行么？或者有什么其他的办法么？

**Comment by hyansuper** [comment]
可以，在文档异步那里有写
